/**
 * PURPOSE
 *   Render the facts about THIS machine that an agent otherwise re-derives by probing:
 *   the platform, the CPU and memory, and — the case that motivated it — whether a GPU and
 *   a CUDA toolkit exist. An agent that is not told runs `nvidia-smi`, `lspci`, `ls
 *   /dev/nvidia*` and a `torch.cuda.is_available()` before it can start, every session,
 *   and the answer never changes between sessions on one machine.
 *
 *   The facts are written to a file the prompt carries, never into the deployment's rules:
 *   `rules/AGENTS.md` is one copy shared by every machine (two Linux, one Windows, different
 *   hardware) and `kit-update --check` decides convergence by its CONTENT HASH, so a
 *   machine-specific claim there would be wrong on the other machines and would make every
 *   machine look permanently drifted.
 *
 * INPUTS
 *   `machineFacts(options)` — `{ os, env, exists, run, cpus }`, every one injectable so a
 *   test states the machine it is measuring instead of reading the host's. `run(command,
 *   args)` returns a trimmed stdout string or throws.
 *   `renderMachineFacts(options)` — the same options; returns the document text.
 *
 * OUTPUTS
 *   `renderMachineFacts` returns a markdown document, always non-empty: a machine whose GPU
 *   probe failed says so, because "no GPU found" and "the probe could not run" are different
 *   facts and an agent needs to tell them apart. The document carries no timestamp, so two
 *   runs on an unchanged machine produce identical bytes.
 *
 * KEYWORDS
 *   machine facts, gpu, cuda, nvidia, visibility, prompt section, per-machine, kit-update
 *
 * BEHAVIOUR ON EDGE CASES
 *   - `nvidia-smi` absent or failing: `GPU: none detected` plus the reason, never a thrown
 *     error, because a machine without a GPU is the normal case on most deployments.
 *   - A probe that throws: that line reports it as unavailable; the rest of the document is
 *     still rendered.
 *   - `cpus()` that fails: the CPU line reports the count as unknown rather than zero.
 */
import { execFileSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { cpus as osCpus, platform, arch, totalmem } from 'node:os'

/**
 * Run one probe command and return its first useful line.
 *
 * @param command - The binary to run.
 * @param args - Its arguments.
 * @returns The trimmed first line of stdout, or throws.
 */
function defaultRun(command, args) {
  return String(execFileSync(command, args, { encoding: 'utf8', timeout: 4000, stdio: ['ignore', 'pipe', 'ignore'] })).trim()
}

/**
 * The GPU lines for one machine.
 *
 * @param run - The probe runner.
 * @returns An array of lines, the first always `GPU: …`.
 */
function gpuLines(run) {
  try {
    const listing = run('nvidia-smi', ['-L'])
    const devices = listing.split('\n').map((line) => line.trim()).filter((line) => line.length > 0)
    if (devices.length === 0) return ['GPU: none reported by nvidia-smi']
    return [`GPU: ${devices.length} NVIDIA device(s), via nvidia-smi`, ...devices.map((line) => `  - ${line}`)]
  } catch (error) {
    return [`GPU: none detected (nvidia-smi unavailable: ${error === null || error === undefined ? 'unknown reason' : String(error.message ?? error).slice(0, 80)})`]
  }
}

/**
 * Render the machine-facts document.
 *
 * @param options - `{ os, env, exists, run, cpus }`, each optional.
 * @returns The document text.
 */
export function renderMachineFacts(options = {}) {
  const env = options.env ?? process.env
  const exists = options.exists ?? existsSync
  const run = options.run ?? defaultRun
  const countCpus = options.cpus ?? osCpus
  const lines = ['# This machine', '', 'Generated by `kit-update.mjs --apply`. Read it instead of probing: these facts do not change between sessions, and re-deriving them costs a turn each time.', '', `- Platform: ${platform()} ${arch()}`, `- Node: ${process.version}`]
  let count = null
  try {
    const list = countCpus()
    count = Array.isArray(list) ? list.length : null
  } catch {
    count = null
  }
  lines.push(`- CPUs: ${count === null ? 'unknown' : String(count)}`)
  const bytes = totalmem()
  lines.push(`- Memory: ${Math.round(bytes / 1024 ** 3)} GiB`)
  lines.push(...gpuLines(run))
  // The toolkit is separate from the driver: a machine can run nvidia-smi and still have no
  // compiler. `nvcc` is reported because it is the thing an agent hunts for next.
  const cudaHome = typeof env.CUDA_HOME === 'string' && env.CUDA_HOME.length > 0 ? env.CUDA_HOME : null
  let nvcc = null
  try {
    nvcc = run('nvcc', ['--version']).split('\n').find((line) => line.includes('release')) ?? null
  } catch {
    nvcc = null
  }
  lines.push(`- CUDA_HOME: ${cudaHome === null ? 'not set' : cudaHome}${cudaHome !== null && !exists(cudaHome) ? ' (path does not exist)' : ''}`)
  lines.push(`- nvcc: ${nvcc === null ? 'not on PATH' : nvcc.trim()}`)
  lines.push('')
  lines.push('A probe that reports `none detected` means the tool is absent; it does not mean the hardware is hidden. Do not spend a turn re-deriving these.')
  return lines.join('\n')
}
